//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceId { get; set; }
        public int BookingId { get; set; }
        public string Status { get; set; }
        public Nullable<int> SlotId { get; set; }
        public System.DateTime AttendanceTime { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual PTSlot PTSlot { get; set; }
    }
}
