//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Attendance = new HashSet<Attendance>();
        }
    
        public int BookingId { get; set; }
        public int MemberId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> SlotId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> BookingTime { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual GymClass GymClass { get; set; }
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual PTSlot PTSlot { get; set; }
    }
}
