//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class GymClass
    {
        public GymClass()
        {
            this.Booking = new HashSet<Booking>();
            this.Session = new HashSet<Session>();
        }
    
        public int ClassId { get; set; }
        public string Name { get; set; }
        public string ClassType { get; set; }
        public int TrainerId { get; set; }
        public string Description { get; set; }
        public Nullable<int> DurationMinutes { get; set; }
        public int Capacity { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string RecurrenceDays { get; set; }
        public Nullable<System.TimeSpan> TimeFrom { get; set; }
        public Nullable<System.TimeSpan> TimeTo { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Session> Session { get; set; }
    }
}
