//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberPackage
    {
        public int MemberPackageId { get; set; }
        public int MemberId { get; set; }
        public int PackageId { get; set; }
        public int SessionsRemaining { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Package Package { get; set; }
    }
}
