//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GymCenterDBEntities1 : DbContext
    {
        public GymCenterDBEntities1()
            : base("name=GymCenterDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Booking> Booking { get; set; }
        public DbSet<MemberPackage> MemberPackage { get; set; }
        public DbSet<Notification> Notification { get; set; }
        public DbSet<Package> Package { get; set; }
        public DbSet<RatingHistory> RatingHistory { get; set; }
        public DbSet<Session> Session { get; set; }
        public DbSet<TrainerRating> TrainerRating { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<MemberProfile> MemberProfile { get; set; }
        public DbSet<TrainerProfile> TrainerProfile { get; set; }
        public DbSet<GymClass> GymClass { get; set; }
        public DbSet<Attendance> Attendance { get; set; }
        public DbSet<Specialty> Specialty { get; set; }
        public DbSet<WeeklyPTSchedule> WeeklyPTSchedule { get; set; }
        public DbSet<PTSlot> PTSlot { get; set; }
    }
}
