//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.MemberPackage = new HashSet<MemberPackage>();
        }
    
        public int PackageId { get; set; }
        public string Name { get; set; }
        public string PackageType { get; set; }
        public int TotalSessions { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<MemberPackage> MemberPackage { get; set; }
    }
}
