//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTSlot
    {
        public PTSlot()
        {
            this.Attendance = new HashSet<Attendance>();
            this.Booking = new HashSet<Booking>();
            this.WeeklyPTSchedule = new HashSet<WeeklyPTSchedule>();
        }
    
        public int SlotId { get; set; }
        public int TrainerId { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public int TotalSessions { get; set; }
    
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual ICollection<WeeklyPTSchedule> WeeklyPTSchedule { get; set; }
    }
}
