//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingHistory
    {
        public int HistoryId { get; set; }
        public int RatingId { get; set; }
        public Nullable<int> PreviousRating { get; set; }
        public string PreviousComment { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual TrainerRating TrainerRating { get; set; }
    }
}
