//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialty
    {
        public Specialty()
        {
            this.TrainerProfile = new HashSet<TrainerProfile>();
        }
    
        public int SpecialtyId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<TrainerProfile> TrainerProfile { get; set; }
    }
}
