//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerProfile
    {
        public TrainerProfile()
        {
            this.Specialty = new HashSet<Specialty>();
        }
    
        public int TrainerId { get; set; }
        public string Avatar { get; set; }
        public string Description { get; set; }
        public Nullable<int> ExperienceYears { get; set; }
        public string Specialties { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsAvailableForPT { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Specialty> Specialty { get; set; }
    }
}
