//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Booking = new HashSet<Booking>();
            this.MemberPackage = new HashSet<MemberPackage>();
            this.Notification = new HashSet<Notification>();
            this.TrainerRating = new HashSet<TrainerRating>();
            this.TrainerRating1 = new HashSet<TrainerRating>();
            this.GymClass = new HashSet<GymClass>();
            this.WeeklyPTSchedule = new HashSet<WeeklyPTSchedule>();
            this.PTSlot = new HashSet<PTSlot>();
            this.PTSlot1 = new HashSet<PTSlot>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Role { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual ICollection<MemberPackage> MemberPackage { get; set; }
        public virtual ICollection<Notification> Notification { get; set; }
        public virtual ICollection<TrainerRating> TrainerRating { get; set; }
        public virtual ICollection<TrainerRating> TrainerRating1 { get; set; }
        public virtual MemberProfile MemberProfile { get; set; }
        public virtual TrainerProfile TrainerProfile { get; set; }
        public virtual ICollection<GymClass> GymClass { get; set; }
        public virtual ICollection<WeeklyPTSchedule> WeeklyPTSchedule { get; set; }
        public virtual ICollection<PTSlot> PTSlot { get; set; }
        public virtual ICollection<PTSlot> PTSlot1 { get; set; }
    }
}
